#!/bin/bash

# Set background image with feh
feh --bg-scale /home/dewei/Pictures/Idlqh99-ubuntu-desktop-background.jpg

# Set mousepad drag lock on (change to appropriate device id)
xinput set-prop 11 "Synaptics Locked Drags" 1
